name: Massimo Pinto, Research Scientist
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: Europe/Rome
gems:
  - jekyll-sitemap
  - jekyll-textile-converter
excerpt_separator: "" #Over-rides any excerpt_separator, see https://jekyllrb.com/docs/posts/#post-excerpts
